# Generated by Django 2.2 on 2021-06-04 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses_app.Course')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
    ]
